version: "3.7"

services:
  app:
    image: ghcr.io/nexters/nextershp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    env_file:
      - .env
    volumes:
      - ./content:/var/www/app/content
    restart: always
