version: "3.7"

services:
  content-updater:
    image: python:3.6-alpine
    working_dir: /app
    entrypoint: ["sh", "content_generator/entrypoint.sh"]
    env_file:
      - .env
    volumes:
      - ./content_generator:/app/content_generator
      - ./content:/app/content
      - ./assets:/app/assets
  app:
    image: ghcr.io/nexters/nextershp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    volumes:
      - ./content:/var/www/app/content
    restart: always
    depends_on:
      - content-updater
